### ISSUE TITLE
All occurrences of then in a condition is failing

### ISSUE THREAD

**Issue by vbasky** [TwitchBronBron/vscode-brightscript-language#102]
It says Expected statement or function call, but received an expression

<img width="726" alt="screen shot 2019-03-05 at 10 20 01 am" src="https://user-images.githubusercontent.com/287302/53769791-0f0d7b80-3f31-11e9-8341-bb979727c5fb.png">

Version: 1.9.0-beta5

**Comment by TwitchBronBron** [comment]
Closing as this appears to be the same underlying issue as #101.
