### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by srinivasantivo** [TwitchBronBron/vscode-brightscript-language#107]
- Issue Type: `Performance`
- Extension Name: `brightscript`
- Extension Version: `1.8.4`
- OS Version: `Linux x64 4.15.0-46-generic`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/harinni/celsoaf.brightscript-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by TwitchBronBron** [comment]
I see you already closed this. Did you figure out what the issue was?
