### ISSUE TITLE
Unable to find a method already defined/implemented

### ISSUE THREAD

**Issue by vbasky** [TwitchBronBron/vscode-brightscript-language#108]
I am not sure why the function call isn't able to find the method in the project

<img width="739" alt="Screen Shot 2019-03-10 at 10 25 37 am" src="https://user-images.githubusercontent.com/287302/54078617-3d1f0100-431f-11e9-8737-4e8f3c69a709.png">

**Comment by vbasky** [comment]
This is a pesky bug can't get to the bottom of this

**Comment by TwitchBronBron** [comment]
it's possible the parse errors in screen_login.brs causes the enableForgot to drop out of the AST.

As a test, can you comment out EVERYTHING in screen_login.brs, and then add this to the very top: 

```
Sub Screen login(param as Boolean)

End sub
```

Does the error on shared_login.brs line 196 go away?

**Comment by vbasky** [comment]
Do you mean add 

```
Sub enableForgot(param As Boolean)

End Sub
```

Either which ways even after getting rid of every other line and adding just this Sub the `shared_login.brs` still shows the error in line 196

**Comment by TwitchBronBron** [comment]
Oops, yeah that's what I meant. 

Can you verify that `screen_login.brs` will be correctly matched by your `files` array from brsconfig.json? 

It uses these globs by default: 

```
"files": [
    "manifest",
    "source/**/*.*",
    "components/**/*.*",
    "images/**/*.*"
]
```

**Comment by TwitchBronBron** [comment]
@vbasky is this still an issue?

**Comment by vbasky** [comment]
No I can happily close this issue. I don't see this error any more.
