### ISSUE TITLE
Valid variable name shown as invalid 

### ISSUE THREAD

**Issue by vbasky** [TwitchBronBron/vscode-brightscript-language#109]
I am not sure if these valid variable name scenarios have been raised before

<img width="531" alt="Screen Shot 2019-03-11 at 11 34 35 am" src="https://user-images.githubusercontent.com/287302/54094013-a7a07180-43f1-11e9-8d39-21be78175684.png">

**Comment by TwitchBronBron** [comment]
Thanks for bringing it up. That's another parser bug, which is tracked by [this issue](https://github.com/sjbarag/brs/issues/162) in the `brs` project. Once it gets fixed in `brs` we should get the fix for free by upgrading.

**Comment by vbasky** [comment]
Adding one more scenario though the issue linked in brs has the expressions, variables link that you have added

<img width="635" alt="Screen Shot 2019-03-13 at 3 26 36 pm" src="https://user-images.githubusercontent.com/287302/54253766-c98e2580-45a4-11e9-9925-cc22d0c2f15f.png">

**Comment by TwitchBronBron** [comment]
Thanks, these are being tracked here: https://github.com/sjbarag/brs/issues/162

**Comment by TwitchBronBron** [comment]
This should be fixed now. Let me know if it's still an issue.
