### ISSUE TITLE
Valid file reference not found

### ISSUE THREAD

**Issue by vbasky** [TwitchBronBron/vscode-brightscript-language#110]
This is the opposite of the error #108 

<img width="1110" alt="Screen Shot 2019-03-11 at 2 24 18 pm" src="https://user-images.githubusercontent.com/287302/54098729-d9bdcd80-4409-11e9-8c6c-fe261942f22e.png">

**Comment by TwitchBronBron** [comment]
This error is on purpose. If you read the error message, it says that this file is not being loaded anywhere in your project. All files in `source` are loaded into the program. Then, every script that every component references is also loaded into the program. 

This warning means your `shared_dash.brs` script is not located in `sources` and is not referenced by any component....therefore it won't actually be available for use anywhere.

**Comment by TwitchBronBron** [comment]
Can you test this again using `1.9.0-beta9`? There was a pretty big regression issue in `1.9.0-beta8`, so I'm hoping that was the reason for the issues you are seeing.

**Comment by vbasky** [comment]
Don't see this happen in `1.9.0-beta9`

**Comment by TwitchBronBron** [comment]
@vbasky has this been resolved?

**Comment by vbasky** [comment]
Yes
