### ISSUE TITLE
Allow using settings.json for launch configs broken in version 1.9.0-beta8

### ISSUE THREAD

**Issue by triwav** [TwitchBronBron/vscode-brightscript-language#111]
You can provide launch configurations in your settings.json file by wrapping in launch key. This works fine in 1.9.0-beta7 but was broken in 8. An example configuration is below.
```
"launch": {
        "configurations": [
            {
                "type": "brightscript",
                "request": "launch",
                "name": "BrightScript Debug: Launch 4K",
                "host": "<IP>",
                "password": "<PASS>",
                "files":[
                    "manifest",
                    "source/**/*.*",
                    "components/**/*.*",
                    "fonts/**/*.*",
                    "images/**/*.*",
                    "config.json"
                ],
                "rootDir" : "${workspaceFolder}"
            }
        ]
    }
```

**Comment by TwitchBronBron** [comment]
I found the issue. When you run a launch configuration from user settings, vscode doesn't know which workspace you are launching it for, so the `folder` variable is undefined. That causes [this line](https://github.com/TwitchBronBron/vscode-brightscript-language/blob/a26836d2bdb3bdfc9aa8f3b76a12361b1b33dcd0/src/DebugConfigurationProvider.ts#L36) to fail. 

This is fixed, so it should land in the next beta release.

**Comment by TwitchBronBron** [comment]
With this specific scenario, I had to code a few different ways to try and get at the workspace folder path. 


1. Use `folder` param if provided (should be present anytime a launch.json debug is started)
2. If there's only one workspace loaded in vscode, use that workspace (should catch almost everything else)
3. If there are more than one workspaces open, prompt the user to specify which workspace they wish to use. 

If the user gets to number 3 and is annoyed, their only recourse is to create a launch.json, but I think that's a fair tradeoff.

**Comment by TwitchBronBron** [comment]
This was fixed in `languageserver-beta10`
