### ISSUE TITLE
LSP gives errors for functions imported in extended component

### ISSUE THREAD

**Issue by georgejecook** [TwitchBronBron/vscode-brightscript-language#118]
Using 1.9.0-beta11, I get problems falsely reported for any functions which are defined in imports from the parent's parent's script file

`BaseScreen` has function definition for `executeSelection`, and imports `log.brs` with a definition for `log_info`
`DiscoverScreen` extend's `BaseScreen`

calls to `executeSelection` and `log_info` are wrongly marked as problem's

**Comment by TwitchBronBron** [comment]
Just to clarify, you are that with this inheritance chain: 
Child -> Parent -> Grandparent, child can see parent functions but child cannot see grandparent functions?

**Comment by georgejecook** [comment]
this might be because of my brsconfig.json being wrong - I didn't have one when I raised this issue, and now I've got one and I get no red squiggles (i.e. problems) at all  - looks like it's not working. I'll try and work out what's going on later today and update

**Comment by georgejecook** [comment]
it's because I import a pkg file, which doesn't get picked up

The method's which are missing come from this import in BaseView.xml

`  <script type="text/brightscript" uri="pkg:/components/Log/Log.brs" />`

the LSP reports this can't be found: it does exist at `src/components/Log/Log.brs`

here's my brsconfig.json
```
{
  "files": [
    "src/**/*.*"
  ]
}
```

**Comment by TwitchBronBron** [comment]
For clarification, are you saying that baseview.xml shows an error on the script import line? 

If you open log.brs in vscode and add a space and save...does that trick the lsp into seeing the file now?

As another testing step, try using a relative path to log.brs and see if that works (adjust for actual file structure) (`src="../../Log/Log.brs"`)

**Comment by georgejecook** [comment]
changing to `../../Log` does fix it

**Comment by georgejecook** [comment]
I've found that all pkg imports are broken in my project.

**Comment by TwitchBronBron** [comment]
Good to know! I designed this to work with both relative and pkg imports... But obviously something got broken. :) I'm look into it.

**Comment by TwitchBronBron** [comment]
@georgejecook is this still an issue?

**Comment by georgejecook** [comment]
nope
