### ISSUE TITLE
Release Methodology 

### ISSUE THREAD

**Issue by TwitchBronBron** [TwitchBronBron/vscode-brightscript-language#12]
This issue is a place to discuss how this project should handle releases. Should there be some type of release cadence, or should releases be done on-demand as new features arrive.

**Comment by TwitchBronBron** [comment]
> It’d be good to know how/when you plan to update
your plugin to include these changes and perhaps plan some cadence for
updates?

I'm open to some type of weekly/semi-weekly/monthly release cadence (obviously skipping any of those iterations that haven't had changes). However, since this is a lower-key project, I would think getting releases out as soon as new features arrive would be more preferable? 

In general, I wouldn't see any benefit in hoarding changes and pushing off releases. I usually try to release whenever a new feature arrives in master. I already have the build process set up to auto-release whenever I tag master, so releasing is easy. The biggest concern is that we don't push out buggy/incomplete code. If we meet that goal, I'm open to suggestions on release schedules/styles/etc. 

I do value my time with family and extra-curriculars, and I can't work on this project during working hours, but I definitely have a few free hours every week where I could handle PRs and releases and such. 

Thoughts?

**Comment by georgejecook** [comment]
Sounds good to me. Informal releases when you've got time, is way more desirable than big planned milestones. We can revisit later, as you require.

I'm totally dog-fooding as well, and with the active guys on slack starting to use it, this will help as well.

are you on the slack channel? there's a #tooling channel in there.

**Comment by pixshatterer** [comment]
+1 to what @georgejecook said

**Comment by TwitchBronBron** [comment]
Yeah I'll close this.
