### ISSUE TITLE
Improve links to files in console output

### ISSUE THREAD

**Issue by georgejecook** [TwitchBronBron/vscode-brightscript-language#13]
Would be handy if they were highlighted, and hyperlinks like in eclipse plugin - this makes it easy to go straight to compile errors.

**Comment by georgejecook** [comment]
can you assign this to me @TwitchBronBron ? I'm happy to implement it.

**Comment by TwitchBronBron** [comment]
Should be fixed when #75 is completed. Don't use the debug console though, use the BrightScript Log output channel.

**Comment by TwitchBronBron** [comment]
Fixed by #75
