### ISSUE TITLE
GOTO statment flagged as errors

### ISSUE THREAD

**Issue by chrisdp** [TwitchBronBron/vscode-brightscript-language#134]
![image](https://user-images.githubusercontent.com/9591618/55628390-f938e380-5786-11e9-9706-3a3cf2c214f7.png)
Flagged as:
Found unexpected token 'GOTO'brs(1000)

v9990.0-languageserver-beta14

**Comment by TwitchBronBron** [comment]
Thanks. This is an issue in the underlying parser, and is tracked [here](https://github.com/sjbarag/brs/issues/158). When it lands in `brs`, it will be a simple nom update to fix it here.
