### ISSUE TITLE
AA keys not displayed properly when hovering

### ISSUE THREAD

**Issue by triwav** [TwitchBronBron/vscode-brightscript-language#137]
If you have an AA with a key of either an `&` symbol or space it doesn't display properly. For the following:
```
"Food & Both":{...},
"Food&And":{...},
"Food Space":{...}
```

The output on hover is:
```
Both: <Component: roAssociativeArray>
Space: <Component: roAssociativeArray>
And: <Component: roAssociativeArray>
```

If you have multiple keys with the same last part that's actually displayed it will actually only return one of these results as well.

**Comment by TwitchBronBron** [comment]
Fixed in 1.13.0
