### ISSUE TITLE
Can't create pure screensaver

### ISSUE THREAD

**Issue by John-Whitehead** [TwitchBronBron/vscode-brightscript-language#148]
A 'pure' Roku screensaver uses RunScreenSaver() as its entry point.  There are no main() or RunUserInterface() functions in a pure screensaver.  A pure screensaver is not listed as a channel, only on the Screensavers page.

I created a pure screensaver using the extension and when I go to run it I see an error - "Unable to find an entry point. Please make sure that you have a RunUserInterface or Main sub/function declared in your BrightScript project."

Please update the extension to support pure screensavers.

**Comment by chrisdp** [comment]
@TwitchBronBron This should now be supported with the merge of PR #149 Can this issue be closed?

**Comment by TwitchBronBron** [comment]
@chrisdp yeah, it should be closed. Thanks.
