### ISSUE TITLE
Jump to file on compile error and display error details.

### ISSUE THREAD

**Issue by chrisdp** [TwitchBronBron/vscode-brightscript-language#153]
When encountering a compile problem when side loading it appears we may have enough info to infer what file contains the issue and for script files possibly even jump to the line.

Also when detecting this type of error we should show a VS Code error with the details rather then just `Error, statusCode other than 200: 400`.

**Comment by chrisdp** [comment]
PR opened that will address this #179

**Comment by TwitchBronBron** [comment]
Fixed by #179
