### ISSUE TITLE
Debugger can't handle an roList

### ISSUE THREAD

**Issue by kbunch** [TwitchBronBron/vscode-brightscript-language#155]
If you try to inspect an roList it cause the debugger to cease working and attempts to connect/deploy to cease working until you restart the device.

Here is a simple use case

```
url = "http://foo.com?test=dude&bob=true"
regex = CreateObject("roRegex", "\?(.*)?$", "")
foo = regex.split(url)

print foo
```

Put a breakpoint at print and hover over foo, it will cause the debugger to go wonky

**Comment by TwitchBronBron** [comment]
Fixed by #160
