### ISSUE TITLE
Support for auto naming outFiles from manifest

### ISSUE THREAD

**Issue by iObject** [TwitchBronBron/vscode-brightscript-language#163]
Requesting support for outfiles (including component libraries) to automatically be named based on the manifest.

Example: `${title}_${major_version}_${minor_version}_${build_version}`

**Comment by chrisdp** [comment]
@iObject would
It be sufficient if the values where derived from the manifest by the keys entered. This way you could also add your own custom key to the manifest and that could be used.

**Comment by chrisdp** [comment]
PR opened here for this issue: #181

**Comment by TwitchBronBron** [comment]
Resolved by #181
