### ISSUE TITLE
No User-Agent header when doing ECP requests

### ISSUE THREAD

**Issue by christinabrien** [TwitchBronBron/vscode-brightscript-language#168]
I noticed a lot of network traffic caused by queries that I tracked down to this plugin. It was made harder to identify because the HTTP requests have no User-Agent string.

query from 10.20.24.54:47878:
GET //query/device-info HTTP/1.1
'Host': '10.20.24.192:8060'
'Connection': 'close'

**Comment by chrisdp** [comment]
Thanks for opening this issue. I worked on the feature that makes this call so I can work on added a change for this. 

I might not be able to get to this till the beginning of next week due to moving this week.

**Comment by TwitchBronBron** [comment]
@christinabrien, what would you recommend adding as the text for the user agent string? I definitely agree that we need some way of making these requests more easily identifiable.

**Comment by chrisdp** [comment]
Also, just to add to this, if the device discovery is causing network problems you can disable it with the user setting: “brightscript.deviceDiscovery.enabled”: false

**Comment by christinabrien** [comment]
It doesn't matter *what* the UserAgent is, as long as it is a unique string that can be identified as belonging to this project. "github.com/TwitchBronBron/vscode-brightscript-language" would do.

**Comment by chrisdp** [comment]
PR created for this issue #173

**Comment by TwitchBronBron** [comment]
Resolved by #173
