### ISSUE TITLE
Include fonts in builds

### ISSUE THREAD

**Issue by jonnyijapan** [TwitchBronBron/vscode-brightscript-language#178]
I noticed that fonts residing in `/fonts` are not included in builds. I had to put the font files (ttf) in components folder or they wouldn't copy.

**Comment by chrisdp** [comment]
Font's are supported they are just not part of the default files array. The default included files glob is the following:

```
      [
        "manifest",
        "source/**/*.*",
        "components/**/*.*",
        "images/**/*.*"
      ]
```

**Comment by TwitchBronBron** [comment]
@chrisdp Is the `fonts` folder a special folder like `source` and `components` or is it just a regular folder?

**Comment by chrisdp** [comment]
I don’t believe fonts is a special folder.

**Comment by TwitchBronBron** [comment]
Ok. In that case, then the answer @chrisdp provided is correct. @jonnyijapan this isn't something we will fix in the extension, but is something you can easily override in your launch configuration. Just add the fonts folder to your files array and you should be good to go.

**Comment by valrenhale** [comment]
Where can you find the files array?

**Comment by TwitchBronBron** [comment]
In the `.vscode/launch.json` file, under your "brightscript" launch type, there's an option for "files". Here's a full example in case you don't have one set up already. 

```javascript
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "BrightScript Debug: Launch",
            "type": "brightscript",
            "request": "launch",
            "host": "${promptForHost}",
            "password": "${promptForPassword}",
            "rootDir": "${workspaceFolder}",
            "files": [
                "manifest",
                "source/**/*",
                "components/**/*",
                "images/**/*",
                "fonts/**/*" // <-- add this to include fonts
            ]
        }
    ]
}


```

**Comment by TonyNguwin** [comment]
I agree with Valrenhale.

**Comment by TwitchBronBron** [comment]
Ah. That's a different problem than the files missing from builds.

For this, you need to help the vscode language server understand your project structure. Create a `bsconfig.json` at the root of your project and give it more information about all of your files. Something like this would probably do the trick assuming you have a standard project setup.

```javascript
{
    "rootDir": "./roku-app", //the root directory of your roku project. use "./" if your project is the same directory as this file
    "files": [
        "manifest",
        "source/**/*.*",
        "components/**/*.*",
        "images/**/*.*",
        "fonts/**/*"
    ]
}
```
