### ISSUE TITLE
can we get better compile error notifications?

### ISSUE THREAD

**Issue by georgejecook** [TwitchBronBron/vscode-brightscript-language#18]
Currently, we get a dialog box - it's not great to work with...

I tinkered with using diagnostics.. It would mean getting the list of compile errors, and updating the compile collection for each of the mentioned documents, as such:

**Comment by TwitchBronBron** [comment]
Yeah, definitely interested in this. Love the idea. I will take a look at it tomorrow if you haven't stayed up all night fixing it by then. 😉

**Comment by georgejecook** [comment]
WIP commit. Easier to see than my other branch, now that you merged all my other contributions down: https://github.com/TwitchBronBron/vscode-brightscript-language/pull/19

**Comment by georgejecook** [comment]
can you assign this to me @TwitchBronBron ? I've got a WIP PR which I'll add tests to this week.

**Comment by georgejecook** [comment]
This is resolved
