### ISSUE TITLE
roku deploy

### ISSUE THREAD

**Issue by jonnyijapan** [TwitchBronBron/vscode-brightscript-language#191]
I can't get roku-deploy to find its configuration file `rokudeploy.json` when using this plugin.

From what I understand roku-deploy.json needs to be in the same folder as the manifest file. But it seems like it doesn't find it, because it's not bumping the build version as expected.

My roku-deploy.json looks like this

```
{
	"incrementBuildNumber": true
}
```

**Comment by TwitchBronBron** [comment]
@jonnyijapan `rokudeploy.json` needs to be at the root folder where you are executing `roku-deploy` from...which is not necessarily the same location as your `manifest` file. If `rokudeploy.json` is a level or two above the folder where your `manifest` lives, you should set the `rootDir` property of `rokudeploy.json` so `roku-deploy` can find your project.

**Comment by jonnyijapan** [comment]
When using roku-deploy standalone, it works well placing `rokudeploy.json` next to `manifest`. But rokudeploy.json is ignored when installing using this extension (vscode-brightscript-language). Maybe there's no way to use the roku-deploy options when launching/deploying using vscode and vscode-brightscript-language?

**Comment by jonnyijapan** [comment]
Found out this doesn't work.
