### ISSUE TITLE
Support completion on <script> tag

### ISSUE THREAD

**Issue by georgejecook** [TwitchBronBron/vscode-brightscript-language#34]
should be possible to autocomplete a filename to get options of full paths for a script tag.

e.g. in an xml file, typing the following 

```  <script type="text/brightscript" uri="NetMixi" />```

and activating  completing should result in:

```  <script type="text/brightscript" uri="pkg:/source/Mixins/NetMixin.brs" />```

**Comment by evgygor** [comment]
My solution:
By the default VSCODE doesn’t support formatting of the XML files.

There are two extension that closes this gap:
1.	XML Tools (by Josh Johnson) – provides basic XML formatting.
2.	Auto Close Tag (by Jun Han) – auto closes tags

Installation – via vscode extensions.

Configuration – add the following lines to the C:\Users\<USER>\AppData\Roaming\Code\User\settings.json and reload the vscode.

```
"auto-close-tag.fullMode": true,
"auto-close-tag.enableAutoCloseSelfClosingTag": false,
"xmlTools.enforcePrettySelfClosingTagOnFormat": true
```

Usage:
•	Formatting XML file – Alt+Shift+F

•	Auto close tags:
o	Type “<” -> type tag_name -> type “>” will create  <tag_name></tag_name>  and the cursor will be located between the tags
o	Type “<” -> type tag_name -> type “/” will create self closed <tag_name />

**Comment by georgejecook** [comment]
This doesn't address the issue though. The plugins you suggest don't
understand PKG URI resolution, nor the root folder config of the
brightscript plugin. I suggest you read my issue again and look at the code
example provided to fully understand what I'm proposing.

**Comment by evgygor** [comment]
It was workaround for xml management and formatting :)

**Comment by georgejecook** [comment]
Yes. I appreciate that; but that's just noise as far as the ticket is
concerned. I already have several xml plugons as I imagine do most vscode
users.

You could just as well suggest an xml coloriser plugin: it had nothing to
do with the actual issue and has now taken the real conversation on a
tangent : worse still, a busy maintainer may have skimmed your comment and
closwd  the issue, which means I have spend my precious time clarifying
your misdirection.

Its good etiquette to keep conversations; especially specific, exampled
feature requests or bug reports on point.

**Comment by evgygor** [comment]
You are little bit aggressive :)
Take a deep breath, we all want this beautiful program to be even better ;-)

**Comment by georgejecook** [comment]
??

If you take professional criticism as aggression that's your personal choice. Perhaps English is not your first language and you struggled to understand my examples. I apologize if I'm did something that enabled you to misconstrue constructive feedback re: your git conduct as aggression. 

I will further add that I think calling someone a little bit aggressive is absolutely unacceptable. Name calling is _not cool_.  This is a totally unreasonable response to my detailed, explicit, calm and polite request for you to to have better git manners.

**Comment by evgygor** [comment]
Apologies accepted.
Thanks.

**Comment by TwitchBronBron** [comment]
This is available in the languageserver beta.
