### ISSUE TITLE
Debug/Deploy fails to make 'out' dir on macOS

### ISSUE THREAD

**Issue by claysquareninety** [TwitchBronBron/vscode-brightscript-language#44]
`vs code EACCES: permission denied, mkdir '/out'`

This occurs in 1.3.0 on macOS High Sierra (10.13.2) regardless of the owner and permissions of my workspace folder, existing 'out' directory, etc. Downgrading to vscode-brightscript-language@1.2.2 fixes this issue for me.

Now that I look at the error message again, is it trying to create my 'out' dir in '/'? Is there a new setting for this?

**Comment by claysquareninety** [comment]
Yes, that's what it was set to:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
...
        {
            "type": "brightscript",
            "request": "launch",
            "name": "Home-express",
            "host": "xxx.xxx.xxx.xxx",
            "password": "xxxx",
            "rootDir": "${workspaceFolder}",
            "consoleOutput": "normal"
        },
...
    ]
}
```

**Comment by TwitchBronBron** [comment]
@claysquareninety version 1.3.1 of the extension resolved this issue. Try it out and let me know if that resolved the issue for you!

**Comment by claysquareninety** [comment]
Works great, thanks!
