### ISSUE TITLE
Need an option to include extra files in deploy

### ISSUE THREAD

**Issue by kbunch** [TwitchBronBron/vscode-brightscript-language#5]
We include other files in our deploy, config files, etc. It seems like roku_deploy has options to add these in, but I at first glance I'm not seeing the option for the launch.json in the extension.

**Comment by kbunch** [comment]
@TwitchBronBron Best scenario would be defining files and what the would map to in the end output vs simply the files to include (since some mappings might be different). Currently we have custom build scripts that create "flavors" of the app. 
For example, we may have 
flavors/shared/resources/fonts
flavors/spanish/prod/resources/config/config.json
flavors/spanish/dev/resources/config/config.json

We'd want to map each resources folder to the root resources/.....
We'd merge shared and prod or shared and dev. By allowing mapping of the files/folders we could pull this off with the extension by simply having different configurations. ex: spanish-dev, spanish-prod, english-prod, etc

**Comment by kbunch** [comment]
It appears that adding a rokudeploy.json doesn't work, but the files property although "not supported" does work as a pass thru. The only issue is that the file paths don't all resolve correctly and we can't map them. Thus it seems like the change may be less on this project and more on roku deploy. Looking into this some.

**Comment by kbunch** [comment]
@TwitchBronBron I was able to make a simple change to the roku deploy script where rather than create absolute paths for ever file within a folder, etc that it just copied complete directories (which is probably way more efficient). In addition, I allowed the definition of src and dest for the files entry. All of this works like a charm and makes me very happy. Hopefully you can add this in and make it official. 
Below is a sample of what a launch.json might look like with various stubs so you can see what I'm doing

`
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "brightscript",
            "request": "launch",
            "name": "flavor1-staging",
            "stopOnEntry": true,
            "host": "XXXXXX",
            "password": "XXXXXX",
            "rootDir": "${workspaceFolder}",
            "files" : [
                {
                    "src":"flavors/flavor1/manifest", 
                    "dest" : "manifest"
                },
                {
                    "src":"flavors/flavor1/resources", 
                    "dest" : "resources"
                },
                {
                    "src":"components", 
                    "dest" : "components"
                },
                {
                    "src":"source", 
                    "dest" : "source"
                },
                {
                    "src":"flavors/flavor1/staging/ADBMobileConfig.json", 
                    "dest" : "ADBMobileConfig.json"
                },
                {
                    "src":"flavors/flavor1/staging/config.json", 
                    "dest" : "resources/config.json"
                },
            ],
            "consoleOutput": "normal"
        }
    ]
}
`

**Comment by TwitchBronBron** [comment]
I like it! Would you be willing to submit a pull request to the[ roku-deploy](https://github.com/TwitchBronBron/roku-deploy) project with your changes? Then I will update the task information for this extension to make it more obvious which roku-deploy settings can be specified in the launch configuration.

**Comment by TwitchBronBron** [comment]
@kbunch I finally got some time to put this together. I updated the `roku-deploy` project with your proposed {src;dest;} concept. Could you `npm install` the latest version of `roku-deploy` ([v0.2.0-beta1](https://www.npmjs.com/package/roku-deploy/v/0.2.0-beta1)) directly in your project and run a few tests to make sure it solves your issues? I don't want to release a new version of vscode-brightscript until I know that roku-deploy solves your issue.

**Comment by avoltis** [comment]
Hi @TwitchBronBron , i wanted to use the same feature, but it gives me an error when trying to add a config file with the "file" property: Property files is not allowed.
Any suggestions?

**Comment by TwitchBronBron** [comment]
@avoltis, this functionality only exists in the `roku-deploy` package right now, and is not yet in the `vscode-brightscript-language` extension. I was hoping that @kbunch would verify that it solves his needs using just `roku-deploy`, then I'll release a new version of `vscode-brightscript-language` with the upgraded `roku-deploy` package.

**Comment by avoltis** [comment]
Hi @TwitchBronBron , just tested with rokudeploy.json included extra files and it is working fine :)  let us know when you release the new version 👍 
Attached config: 
![image](https://user-images.githubusercontent.com/10733288/46078602-f1273800-c194-11e8-8b71-9d6da1b050c7.png)

**Comment by TwitchBronBron** [comment]
@avoltis, I just released version 1.2.1 of the extension which includes this change. Can you test and make sure it's working?

**Comment by avoltis** [comment]
@TwitchBronBron hi, yeah i did test it this morning. It is working 👍 
Thank you !

**Comment by kbunch** [comment]
My apologies, I ran an Ironman this past weekend and have been in CT this week with a client. I'll check when I get home to see if its working how we tweaked it. Many thanks ahead of time!

**Comment by kbunch** [comment]
@TwitchBronBron its working 👍. Have a new request now ;). We write test files to run various tests while we are writing out all the logic. We stuff all of those files under components/test. These get pushed out to the end zip unless we exclude them in some way. Wondering if it makes sense to add an exclude value as a property to src, dest object OR if we add a way to run a post process node script. Thoughts?

**Comment by TwitchBronBron** [comment]
I think you can accomplish this specific use case using a glob pattern (which roku-deploy already supports). 

Change your glob pattern for the components folder to this (include all subfolders EXCEPT the test folder):

```
{
   "src": "components/!(test)/**/*'",
   "dest": ""
}
```

Does that solve your issue?

**Comment by kbunch** [comment]
@TwitchBronBron That doesn't seem to work, trying different patterns, but I can't get it to move all the subfolders over to the components directory. We have folders like... yourdomain/app/content/utils/Foo.brs.
