### ISSUE TITLE
Unable to find an entry point. Please make sure that you have a RunUserInterface or Main sub declared in your BrightScript project

### ISSUE THREAD

**Issue by piyushg098** [TwitchBronBron/vscode-brightscript-language#50]
Getting this error when trying to launch the app with debugging.
My main.brs has function main(args as Dynamic) not sub main() because of Deep linking integration.
![screen shot 2018-12-07 at 12 07 25 pm](https://user-images.githubusercontent.com/17822423/49631618-b5241500-fa18-11e8-81fc-cd8aa95bdb8c.png)

**Comment by TwitchBronBron** [comment]
I'm able to reproduce this locally. I'll work on a fix and try to get a release out in the next day or so. Thanks for bringing this to my attention!

**Comment by piyushg098** [comment]
@TwitchBronBron Could you provide the update link since this one here:
https://code.visualstudio.com/updates/v1_29
Says 1.29 as the latest and I too have this version on my Mac. Check for updates says there's not a one for now.

**Comment by TwitchBronBron** [comment]
The 1.29 you're talking about is the Visual Studio Code version. I meant version 1.3.2 of the vscode-brightscript-language extension (this project). If you go to [this link]( https://marketplace.visualstudio.com/items?itemName=celsoaf.brightscript), you should see the version number in the info on the right.

Also, in your extensions area of Visual Studio Code, it should show you versoin 1.3.2 for this extension.
![image](https://user-images.githubusercontent.com/2544493/49697412-18cb5100-fb85-11e8-9c17-4f642a1ee4c2.png)

**Comment by piyushg098** [comment]
Thanks, @TwitchBronBron . It works now.

**Comment by TwitchBronBron** [comment]
Fantastic! Thanks.
