### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by HeroSpha** [TwitchBronBron/vscode-brightscript-language#6]
Kindly please include how to use this extension. do i have to clone your repo? or i just install it. im new to Brightscript.. im stuck, i cant do anything at all.. The other thing, you mention launch config file, but i dnt know where to put it, and its name. I looked into your repo, there is a launch.json, but its different from the read me. Also can you point out which **host** is required, and what **password**.

**Comment by TwitchBronBron** [comment]
This project is the repository for a "Visual Studio Code" extension. "Visual Studio Code" is an open source editor created and maintained by Microsoft. So you first need to install Visual Studio Code from [here](https://code.visualstudio.com/download). Then, using the Visual Studio Code Extensions tab, install the extension ([here's a tutorial](https://code.visualstudio.com/docs/editor/extension-gallery#_browse-for-extensions)). 

Honestly if you are brand new to BrightScript/Roku development, you may want to follow the official Roku tutorials first until you get familiar with how to develop roku apps. This extension doesn't currently support "starting from scratch" Roku projects, so the official Roku tutorials and their Eclipse plugin holds your hand through that whole process.

**Comment by TwitchBronBron** [comment]
You're welcome! If you find any issues with the extension, please feel free to open another issue!
