### ISSUE TITLE
what's the status of this project/debugging?

### ISSUE THREAD

**Issue by georgejecook** [TwitchBronBron/vscode-brightscript-language#7]
Hi, I can see this is in active development; and that you have an adapter for telnet, which is mighty impressive. 

I've got a plugin which does symbol regonition, defitintions, and some other stuff, which I'm actively working on.. and I'm trying to work out what to do with it.. ~~I'm almost certainly going to roll my own; but thought we should get in touch - we can probably swap features~~ |hang that -yours is already excellent and I don't want another project - I want to submit some prs to you

![sofarsogood](https://user-images.githubusercontent.com/1214545/48650987-cdc77f00-e9c6-11e8-9e72-713a2c4446da.gif)

**Comment by georgejecook** [comment]
Okay - I just tried out your debugger. it's awesome. I've forked, and will park my stuff in there, and send you prs..
you can find me on the roku developer slack group: georgejecook - I made rooibos https://github.com/georgejecook/rooibos/tree/master/docs which I'm going to integrate with vscode..

We should talk - rooibos is a lot of work for me, and I'm always improving my workflow and tools - I'd be happy to muck in with you on this project - perhaps we may have some aligned goals?

**Comment by TwitchBronBron** [comment]
Thanks! I would be more than happy to accept PRs for whatever makes this extension better and makes roku developers' lives easier. Your symbol recognition and definitions would be most welcome! 

Just curious, how do you see rooibos fitting in to this extension?

**Comment by georgejecook** [comment]
I'm going to implement this for rooibos.

I was thinking it would be part of my own vscode Roku plugin but seeing as
yours is so we'll developed i figure it will likely be its own thing now.

https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-mocha-test-adapter

So I'll start contributing symbols and other relevant items to your project
and create this other one for just the rooibos testing aspects in a few
weeks.

**Comment by TwitchBronBron** [comment]
Closing this issue as I think we are already well on our way to integrating many of your changes.
