### ISSUE TITLE
Go to declaration doesn't work for functions with whitespace in front of them

### ISSUE THREAD

**Issue by triwav** [TwitchBronBron/vscode-brightscript-language#82]
Jump To doesn't seem to work when doing string concatenation. As an example in my code. I have `logDebug("focus", "Set focus to " + nodeToString(node))` I can jump to `logDebug` but not `nodeToString`

**Comment by TwitchBronBron** [comment]
Based on our conversations in slack, the issue is actually that function definitions with whitespace in front of them are not picked up by the "what functions are available" checker.
