### ISSUE TITLE
Bitshift Assignment Operators error

### ISSUE THREAD

**Issue by vbasky** [TwitchBronBron/vscode-brightscript-language#95]
<img width="239" alt="screen shot 2019-02-22 at 10 28 47 am" src="https://user-images.githubusercontent.com/287302/53208917-c4684580-368c-11e9-994b-fc00b962df6f.png">

The above valid syntax in bright script is shown as an error in the IDE

Version: 1.9.0-beta1

**Comment by TwitchBronBron** [comment]
Thanks for reporting this! [Here's a ticket](https://github.com/sjbarag/brs/issues/155) on the parser project tracking this issue. Once that fix lands, it should fix the issue in the IDE.
