### ISSUE TITLE
Typo Error in Identifier

### ISSUE THREAD

**Issue by vbasky** [TwitchBronBron/vscode-brightscript-language#96]
![screen shot](https://user-images.githubusercontent.com/287302/53210822-42c7e600-3693-11e9-97ae-928c65ab8f4f.png)

Typo error in identifier

Version: 1.9.0-beta1

**Comment by TwitchBronBron** [comment]
Thanks, I didn't know about this one. I just opened [this ticket](https://github.com/sjbarag/brs/issues/164) on the `brs` parser project. When it gets fixed there, it will trickle down into this project.

**Comment by vbasky** [comment]
@TwitchBronBron Is this handled by https://github.com/sjbarag/brs ?

**Comment by TwitchBronBron** [comment]
Yes, it is. All of the "parser" style errors are handled by https://github.com/sjbarag/brs. 

I just submitted [this](https://github.com/sjbarag/brs/pull/168/files) pull request to fix the typo. Good catch!

**Comment by vbasky** [comment]
> Yes, it is. All of the "parser" style errors are handled by https://github.com/sjbarag/brs. One way to tell is, right now, I just assign every parser error a code of `BRS1000`.
> 
> I just submitted [this pull request](https://github.com/sjbarag/brs/pull/168) to fix the typo. Good catch!

Didn't know that you would be submitting a PR. I submitted the same I'll pull mine off.

**Comment by TwitchBronBron** [comment]
Oops! Sorry. Maybe I should have gone to bed instead... :) 

Thanks for all of your help.

**Comment by vbasky** [comment]
I see that this has been fixed in brs repository is it flowing through here as well ?

**Comment by TwitchBronBron** [comment]
Just pushed release [1.9.0-beta2](https://github.com/TwitchBronBron/vscode-brightscript-language/releases/tag/v1.9.0-beta2).
