### ISSUE TITLE
Valid short hand syntax displayed as error in IDE

### ISSUE THREAD

**Issue by vbasky** [TwitchBronBron/vscode-brightscript-language#97]
Below is the error that I am getting from the IDE which is not really helpful.

<img width="539" alt="screen shot 2019-02-25 at 10 15 32 am" src="https://user-images.githubusercontent.com/287302/53306989-c11cc600-38e7-11e9-81e7-419dd31b7f17.png">

**Comment by TwitchBronBron** [comment]
Thanks. This is an error in the `brs` parser. I have filed an issue in that project.

**Comment by vbasky** [comment]
I can close this issue as it has been fixed in 1.9.0 beta 7
