### ISSUE TITLE
Shouldn't be linting commented lines

### ISSUE THREAD

**Issue by vbasky** [TwitchBronBron/vscode-brightscript-language#99]
The plugin is linting commented lines as well. Ideally it should ignore them in the XML

<img width="797" alt="screen shot 2019-02-25 at 12 16 57 pm" src="https://user-images.githubusercontent.com/287302/53308700-799e3600-38f7-11e9-869b-92ec95884eca.png">

Version: 1.9.0-beta2

**Comment by TwitchBronBron** [comment]
The plugin doesn't have an actual xml parser right now, so I'm just using regex to find all of the script imports. I forgot to take comments into account. Great catch!

**Comment by TwitchBronBron** [comment]
This should be fixed in release `v1.9.0-beta3`
